version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7

    working_directory: ~/myapp

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            bundle install
            yarn install

      - run:
          name: Database setup
          command: |
            bundle exec rails db:create
            bundle exec rails db:migrate

      - run:
          name: Run tests
          command: |
            bundle exec rspec

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
